### ISSUE TITLE
Compatibility with latest XCode versions

### ISSUE THREAD

**Issue by lgrignon** [oscahie/boost2xctest#1]
Hello, this bridge looks nice, but it seems that it does not work with latest version. 
I am running XCode 13.2.1

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/6956079/156134463-18ce0220-0e2d-4dba-af03-997eb43a522a.png">

I hope I didn't miss something. Just for you to know, Unit Tests bundle is linked with app, but nothing shows in tests tab

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/6956079/156135319-eea01938-4225-4531-9da2-b4f54b2f9a97.png">

**Comment by oscahie** [comment]
You need to run all the tests at least once for them to appear in the Xcode UI, have you done that? It works here with the latest Xcode.

**Comment by lgrignon** [comment]
Thanks for your reply @oscahie 
How can I run them if they do not appear? I tried to run using Unit test target and it showed me this 
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/6956079/156156819-c63822ab-e0d5-41c1-90d8-1b4276e9aec7.png">

Also I tried to run the app, but it only starts the empty app and nothing is shown in the UI.

Do you have any clue? 

Thanks again

**Comment by oscahie** [comment]
You may either press CMD+U or click on `Product` -> `Test`

**Comment by lgrignon** [comment]
It works. Thanks!
